spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        ddl-auto: create

  config:
    import: "classpath:API-KEY.yml"
token:
  secret: ${token.secret}
  access_token_expiration_time: ${token.access_token_expiration_time}
  refresh_token_expiration_time: ${token.refresh_token_expiration_time}

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000

springdoc:
  swagger-ui:
    path: /