spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jooq:
    sql-dialect: POSTGRES # 사용할 sql dialect
  redis:
    data:
      host: localhost # Redis 서버 호스트
      port: 6379      # Redis 포트
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        # show_sql: true
        # format_sql: true
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

token:
  secret: ${JWT_SECRET}
  access_token_expiration_time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh_token_expiration_time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  email_token_expiration_time: ${JWT_EMAIL_TOKEN_EXPIRATION_TIME}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: perflow-bucket

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}
    model: ${GEMINI_MODEL_NAME}

fcm:
  service-account:
    type: ${FCM_TYPE}
    project_id: ${FCM_PROJECT_ID}
    private_key_id: ${FCM_PRIVATE_KEY_ID}
    private_key: ${FCM_PRIVATE_KEY}
    client_email: ${FCM_CLIENT_EMAIL}
    client_id: ${FCM_CLIENT_ID}
    auth_uri: ${FCM_AUTH_URI}
    token_uri: ${FCM_TOKEN_URI}
    auth_provider_x509_cert_url: ${FCM_AUTH_PROVIDER_X509_CERT_URL}
    client_x509_cert_url: ${FCM_CLIENT_X509_CERT_URL}
    universe_domain: ${FCM_UNIVERSE_DOMAIN}