spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.password}
  redis:
    data:
      host: localhost # Redis 서버 호스트
      port: 6379      # Redis 포트
  jpa:
    properties:
      hibernate:
        ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  config:
    import: "classpath:API-KEY.yml"

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000

token:
  secret: ${token.secret}
  access_token_expiration_time: ${token.access_token_expiration_time}
  refresh_token_expiration_time: ${token.refresh_token_expiration_time}

springdoc:
  swagger-ui:
    path: /

cloud:
  aws:
    credentials:
      accessKey: ${aws.access}
      secretKey: ${aws.secret}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${aws.bucket}
