spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.password}
  jpa:
    properties:
      hibernate:
        ddl-auto: create
  config:
    import: "classpath:API-KEY.yml"

springdoc:
  swagger-ui:
    path: /